services:
  - type: web
    name: ichancy-bot-pro
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: 8312113931:AAFKlUxshhvrZ9IiMn9Wj4FelfcISj31S9w
        sync: false
      - key: 8146077656
        sync: false
      - key: SYR_CASH_NUMBER
        value: "0990000000"  # ⬅️ غير لرقمك
      - key: SCH_CASH_NUMBER
        value: "0940000000"  # ⬅️ غير لرقمك
      - key: DATABASE_URL
        fromDatabase:
          name: ichancy-db-pro
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ichancy-redis-pro
          property: connectionString

databases:
  - name: ichancy-db-pro
    plan: free
    databaseName: ichancy_pro
    user: ichancy_user

redis:
  - name: ichancy-redis-pro
    plan: free
    maxmemoryPolicy: allkeys-lru
    maxmemory: 100mb